### ISSUE TITLE
Warning "Following value requires an explicit type annotation" for values = findValues

### ISSUE THREAD

**Issue by zeromancer** [lloydmeta/enumeratum#103]
I get a warning "Public value requires an explicit type annotation" for the field
	
	val values = findValues
	
My problem: the moment i change it to 
	
	val values:IndexedSeq[Greeting] = findValues
	
I get a compiler **error**: "value values has incompatible type"

Do i do something wrong or how can i fix this ?
Using: scala2.12, IntellijJ2016.3.3
(I would really like to avoid disabling this type annotation in my IDE, since it is useful everywhere else)

Toy example:

	import enumeratum._

	sealed trait Greeting extends EnumEntry {
	}

	object Greeting extends Enum[Greeting] {
		val values = findValues

		case object Hello extends Greeting

		case object Bue extends Greeting

		case object Hi extends Greeting
	}

**Comment by lloydmeta** [comment]
Hi there,

Good question. The problem is probably because you didn't have the immutable IndexedSeq imported (which is what is explicitly produced by `findValues`).

The following should work:

```scala
import enumeratum._
import scala.collection.immutable.IndexedSeq
  
sealed trait Greeting extends EnumEntry
  
object Greeting extends Enum[Greeting] {
  val values: IndexedSeq[Greeting] = findValues
  
  case object Hello extends Greeting
  
  case object Bue extends Greeting
  
  case object Hi extends Greeting
}
```

Also, I think in IntelliJ, when you have a warning like that, you can put your cursor on that part of the code and hit option+enter (on Mac, not sure of the equiv elsewhere. I also have settings carried over from super old IntelliJ) and choose "Add type annotation", which will automatically find the right one for you.

Let me know if you have any further questions.

Lloyd

**Comment by zeromancer** [comment]
It works
Many thanks for the advice !
