### ISSUE TITLE
AbstractMethodError when decoding with Circe

### ISSUE THREAD

**Issue by brianlow** [lloydmeta/enumeratum#104]
I am having trouble using enumeratum with circe

```
import io.circe._
import io.circe.generic.auto._
import enumeratum.values._

sealed abstract class Action(val value: String, val name: String) extends StringEnumEntry
case object Action extends StringEnum[Action] with StringCirceEnum[Action] {

    case object Buy extends Action("B", "Buy")
    case object Sell extends Action("S", "Sell")

    val values = findValues
}

case class Trade(action: Action)

val t = Trade(Action.Buy)
decode[Trade](t.asJson.toString).fold(throw _, identity)
```

gives:

```
java.lang.AbstractMethodError: enumeratum.values.Circe$$anon$2.tryDecode(Lio/circe/ACursor;)Lscala/util/Either;
	at com.compay.engine.Tester$anon$exportDecoder$macro$48$1$$anon$12.apply(Tester.scala:38)
	at io.circe.generic.decoding.DerivedDecoder$$anon$1.apply(DerivedDecoder.scala:13)
	at io.circe.Decoder$class.decodeJson(Decoder.scala:42)
	at io.circe.generic.decoding.DerivedDecoder.decodeJson(DerivedDecoder.scala:6)
	at io.circe.Parser$class.decode(Parser.scala:10)
	at io.circe.jawn.JawnParser.decode(JawnParser.scala:8)
	....
```

This works when `action` is a String and enumeratum is not used.

**Comment by brianlow** [comment]
This issue doesn't appear with the latest enumeratum + circe

**Comment by lloydmeta** [comment]
I think this kind of error typically happens when there are conflicting versions of the same dependency in a build. Glad you sorted it out.

BTW, depending on how/where you import the generic auto codec derivation for Circe, there's a chance that it might not work properly with enums. One user [had reported](https://github.com/lloydmeta/enumeratum/issues/90) getting a compile time error due to the dependence that mechanism has on `knownDirectSubclasses`. An even worse scenario might be that the proper decoder provided by Enumeratum (the one that deserialises from your values, like "B" and "S"), gets ignored and the one provided by generic.auto is used, which uses .toString (in your example case, uses "Buy" and "Sell").
