### ISSUE TITLE
Why is EnumEntry.entryName a def instead of a val?

### ISSUE THREAD

**Issue by daniel-shuy** [lloydmeta/enumeratum#105]
First off, this is a great library, I hope it will eventually replace the built-in Enumeration in the Scala core library.

This is not really an issue, but as I was diving into to the code, I couldn't help but notice that entryName in EnumEntry is declared as a def. Doesn't that mean that if entryName is not overridden (eg. trait MyEnum extends EnumEntry), it would be re-evaluated each time entryName is used (even worse when a case-manipulating Trait, eg. CapitalSnakecase, is mixed in)?

I'm just curious, is there a reason for this design choice?

**Comment by lloydmeta** [comment]
Good question. 

The reason `def` is used is because you can't actually call `super` on a `val`, which is what we need to do to provide the stackable traits feature.

There is a way around it though: keep `entryName` as a def, but have a `private val` field for each new implementation of that method that computes and holds a stable value, and return that in `entryName` instead.

Would you like to help with this optimisation?

**Comment by lloydmeta** [comment]
I had a bit of time and gave it a stab: turned out to be straightforward so I went ahead and did it.

Thanks for the idea by the way ! ~500x speedup is definitely worth the small increase in complexity :)

**Comment by daniel-shuy** [comment]
Wow thanks for the quick response, I was just about to suggest that workaround myself :)
