### ISSUE TITLE
Macro Annotations

### ISSUE THREAD

**Issue by daniel-shuy** [lloydmeta/enumeratum#109]
I wanted to write an efficient EnumSet/EnumMap for Enumeratum like Java's.

Java's [EnumSet](https://docs.oracle.com/javase/8/docs/api/java/util/EnumSet.html) is essentially a bitmap. EnumSet.contains() uses the index of the Enum entry to perform a bitwise AND operation on the bitmap.

Java's [EnumMap](https://docs.oracle.com/javase/8/docs/api/java/util/EnumMap.html) is essentially an array that stores each Value in the array index corresponding to the index of the Enum entry.

In both cases, to replicate the same behavior, given just an instance of EnumEntry, the Set/Map needs to be able to obtain the index of the EnumEntry. Currently, EnumEntry does not know what its index is.

I've been trying all sorts of ways to pass the index to each instance of EnumEntry without breaking encapsulation. Ideally, if possible, I wanted to do so without changing the way EnumEntry/Enum is used. Since Enum has valuesToIndex, one of the easiest ways to achieve this is to somehow pass the object extending Enum to the sealed trait/abstract class extending EnumEntry.

To avoid changing the way EnumEntry is used, initially I did:
```scala
abstract class EnumEntry()(implicit enum: Enum[_]) {
```
but somehow it didn't work. Even if it did, if there were multiple Enums in the same file, would the implicit enum parameter look-up the wrong Enum object instance?
I then tried:
```scala
abstract class EnumEntry[E <: EnumEntry]()(implicit enum: Enum[E]) {
```
which requires the type of the sealed trait/abstract class to be specified as a Type Parameter, eg. 
```scala
sealed trait MyEnum extends EnumEntry[MyEnum]
```
I then tried to enforce the Type Parameter passed in to be the sealed trait/abstract class instance, and tried to allow the compiler to automatically infer the Type Parameter:
```scala
abstract class EnumEntry[+Self <: EnumEntry]()(implicit enum: Enum[Self]) {
```
or
```scala
abstract class EnumEntry[E <: EnumEntry]()(implicit enum: Enum[E]) {
    self: E =>
```
which can then be used as:
```scala
sealed abstract class MyEnum extends EnumEntry    // must be abstract class to infer Self
```
which would achieve what I want, but unfortunately, I get weird errors when compiling the tests:
> error: not found: value <none>

which I can't for the life of me figure out the meaning of.

---

This then lead me to the idea of using [Macro Annotations](http://docs.scala-lang.org/overviews/macros/annotations.html). If a class is annotated, both the class (sealed abstract class) and companion object is passed to the macro. Theoretically, we can then no longer bother with implicit parameters and pass in the object directly instead. Eg. 
```scala
@Enum
sealed trait Temperature

object Temperature {
    case object Hot extends Temperature
    case object Room extends Temperature
    case object Cold extends Temperature
}
```
should be expanded by the macro to:
```scala
sealed trait Temperature extends EnumEntry(Temperature)    // not sure if you can pass the reference to the companion object like that

object Temperature extends Enum[Temperature] {
    val values = ...

    case object Hot extends Temperature
    case object Room extends Temperature
    case object Cold extends Temperature
}
```
I'm not sure if you can pass the reference to the companion object like that. If not, then maybe the EnumEntry constructor could take in a index: Int instead of an instance of Enum, but I think it may be useful for other purposes for the EnumEntry to have a reference to the Enum companion object.

Note that, in addition to automatically extending EnumEntry/Enum, we can also use the macro to implement values automatically, removing the need to manually call:
```scala
val values = findValues
```
killing 2 birds with one stone.

The downsides are, it breaks backwards compatibility, and implementers of Enumeratum will need to add the Macro Paradise compiler plugin to their project.

**Comment by daniel-shuy** [comment]
After some Googling, it seems that this Enum library, [Numerato](https://github.com/maxaf/numerato), uses Macro Annotations to achieve something similar to my suggestion. It would be cool if we could have the best of both worlds :)

**Comment by lloydmeta** [comment]
If you want to have a method that returns the index of any properly-implemented `EnumEntry` (as in, it is inside a companion object that extends `Enum`), you just need to materialise its companion object.

The following is via Ammonite

```scala
Welcome to the Ammonite Repl 0.8.1
(Scala 2.12.1 Java 1.8.0_101)
@ import $ivy.`com.beachape::enumeratum:1.5.7`, enumeratum._ 
import $ivy.$                               , enumeratum._
@ {
  // Declare 2 enums
  
  sealed trait AgeGroup extends EnumEntry
  
  case object AgeGroup extends Enum[AgeGroup] {
  
    val values = findValues
  
    case object Baby     extends AgeGroup
    case object Toddler  extends AgeGroup
    case object Teenager extends AgeGroup
    case object Adult    extends AgeGroup
    case object Senior   extends AgeGroup
  
  }
  
  sealed abstract class Light extends EnumEntry
  
  case object Light extends Enum[Light] {
    val values = findValues
    case object Red extends Light
    case object Blue extends Light
    case object Green extends Light
  }
  } 
defined trait AgeGroup
defined object AgeGroup
defined class Light
defined object Light
@ {
  // indexOf for any properly-implemented Enum
  def indexOf[A <: EnumEntry: Enum](entry: A): Int  = {
      implicitly[Enum[A]].indexOf(entry)
  }
  } 
defined function indexOf
@ indexOf(Light.Red: Light) 
res3: Int = 0
@  
@   indexOf(AgeGroup.Baby: AgeGroup) 
res4: Int = 0
@  
@   indexOf(AgeGroup.Adult: AgeGroup) 
res5: Int = 3
```

BTW, you'll notice that I had to add a type annotation when passing in each member; this is because otherwise, the value passed to the function will have the singleton type (e.g. `AgeGroup.Adult.type` instead of AgeGroup), which I suspect is what caused the `error: not found: value` error you saw :)

----

As for Macro annotations, I think they're worth exploring. When Enumeratum was written, I avoided macro annotations because IDEs didn't really understand how the macros expanded w/o writing a plugin, but with Scalameta coming around the corner, that has changed (IntelliJ for example can support Scalameta macro annotations fine).

One thing I've seen quite often with the annotation-driven enum solutions is that they exchange power/flexibility in exchange for terseness. What this means is that they usually don't support the full myriad of things that Scala allows you to do, like adhock extend other traits/classes in members (e.g. the way we do stacked traits to manipulate names) or add methods and values to each member, which can come in quite handy.  By the time you can support all these use-cases, you've probably got a fairly huge and complex macro.

If we go down the macro annotation route, I'd like to try our best to keep the flexibility and power that Enumeratum currently affords users. If not all, then at least cover the most important use cases :)

**Comment by daniel-shuy** [comment]
Interesting, I have so much more to learn :)

Good point with the name-manipulating traits, didn't think of that, hmm...maybe it could be replicated with annotation parameters? Haha

Maybe we should wait until Macros is no longer experimental and finally becomes a part of the standard library (hopefully in 2.13?)

**Comment by lloydmeta** [comment]
> Interesting, I have so much more to learn :)

Same here ! To be fair, in this case the error message thrown at compile time was terribly cryptic and not helpful (`error: not found: value`). I've made an attempt to make it nicer with #110.

> Maybe we should wait until Macros is no longer experimental and finally becomes a part of the standard library (hopefully in 2.13?)

I get the feeling that this will be a long ways in the future :). I played around with Scalameta for a while and found that it doesn't yet support things like finding the parent of a given type (for now the recommendation is if you need this kind of functionality, emit an annotation built with the old macro API), and mangles certain for-comprehensions. 

So yeah I'm with you there; probably best to wait until things are more ready.

**Comment by daniel-shuy** [comment]
Just leaving my thoughts here for future reference:

I was just wondering what would the extent of possibilities be with Macro Annotations.

Theoretically, it would even be possible to combine Enum and ValueEnum, and maybe even allow multiple Value keys of different types to be indexed, maybe even with optional unique constraints.

Eg.

```scala
@Enum(CapitalWords)
sealed abstract class Grocery(
    @EnumKey(unique = true)    // should unique default to true/false?
    id: Int, 

    @EnumKey(unique = false)    // should unique default to true/false?
    category: String,

    exampleBool: Boolean
)

object Grocery {
    case object Chicken extends Grocery(101, "Meat", true)
    case object Lamb extends Grocery(102, "Meat", false)
    // case object Pork extends Grocery(102, "Meat", true) <-- will fail to compile because the id 102 must be unique
    case object Coke extends Grocery(201, "Beverage", false)
}
```
would expand to:
```scala
sealed abstract class Grocery(id: Int, category: String, exampleBool: Boolean) extends EnumEntry with CapitalWords

object Grocery extends Enum[Grocery] {
    case object Chicken extends Grocery(101, "Meat")
    case object Lamb extends Grocery(102, "Meat")
    case object Coke extends Grocery(201, "Beverage")

    val values: immutable.IndexedSeq[Grocery] = IndexedSeq(Chicken, Lamb, Coke)
    private val idToEntriesMap: immutable.Map[Int, Grocery] = 
        Map(
            Chicken.id -> Chicken,
            Lamb.id -> Lamb,
            Coke.id -> Coke
        )
    private val categoryToEntriesMap: immutable.Map[String, Set[Grocery]] = ???    // some MultiMap implementation (Scala's MultiMap seems lacking...maybe Google Guava's HashMultimap?)

    def withId(id: Int): Grocery = idToEntriesMap(id)
    def withCategory(category: String): Set[Grocery] = categoryToEntriesMap(category)
}
```

It may even be possible to make the syntax even more concise (see [Numerato](https://github.com/maxaf/numerato))

**Comment by lloydmeta** [comment]
Theoretically, pretty much anything is possible with macros ;) Just take a look at [scala-async](https://github.com/scala/async).  Practically speaking, my experience is that the size and complexity of the macro grows non-linearly with every feature (language level) you want to support because essentially you're on your own building an AST transformer. The difficulty balloons even more when concise syntax is also a goal, which is why most of those brevity-focused libs aren't as powerful.

Having said that, I think your design looks nice and it's worth considering how Enumeratum should evolve in the future. I'll close this issue for now and open another one for the purpose of discussing future designs.

**Comment by daniel-shuy** [comment]
Thanks. I'll also open a new issue for the EnumSet/EnumMap implementation.
