### ISSUE TITLE
Potential addition to Slick integration for easy MappedColumnType[ValueEnum] definitions

### ISSUE THREAD

**Issue by kolemannix** [lloydmeta/enumeratum#135]
First off, I want to say thank you for Enumeratum, it really is The Missing Scala Enum Library (TM), and I wish I had discovered it sooner.

I just thought I would share a little helper trait and function I've been using for defining `MappedColumnTypes` for instances of `ValueEnum[A]` with less boilerplate:

```scala
import scala.reflect.ClassTag
import enumeratum.values.{ ValueEnum, ValueEnumEntry }
import slick.driver.JdbcProfile

trait Profile {
  val profile: JdbcProfile
}

trait MappedColumnTypeEnumSupport { this: Profile =>
  def mappedColumnTypeForValueEnum[V, E <: ValueEnumEntry[V]]
  (companion: ValueEnum[V, E])
  (implicit tag: ClassTag[E], v: profile.BaseColumnType[V]): profile.BaseColumnType[E] = {
    profile.MappedColumnType.base[E, V](
      { x => x.value },
      { v => companion.withValue(v) }
    )
  }
}
```
Usage (assuming a `ValueEnum` called `Shape` somewhere in scope): 
```scala
trait MyMappers extends MappedColumnTypeEnumSupport {
  implicit lazy val shapeMapping: BaseColumnType[Shape] = mappedColumnTypeForValueEnum(Shape)
}
```

Seems like this is generic enough that it could potentially be included with the library to ease this use case?If so, I believe something similar could be done for the `SetParameter` definitions as well.

Thanks again for this great library!

**Comment by lloydmeta** [comment]
Hi there,

Thanks for your kind feedback :)

Your Slick integration looks good to me; I think it would be great to have that included so users don't need to write that boilerplate themselves. 

Would you be interested in adding such an integration?

**Comment by kolemannix** [comment]
@lloydmeta 
I'd be happy to add an integration. I'll mention though, that I am a fan of separating Serialization concerns such as a `BaseTypedType` from definition of the data model. Thus, if I wrote an integration, it would probably not be of the mix-in style where the trait is mixed right in at the site the enum is defined. It just seems to couple them very tightly, and does not work if you have no control of the call-site, say if I wanted a `BaseTypedType` for an enum defined in a 3rd party library.

So more of a typeclass-instance-style interaction, where instances are defined in an ad-hoc fashion separately.

Just thought I'd mention this, since the Play JSON integration is mix-in style, and consistency is important. I'm happy to build both styles for consistency's sake. We can close the issue and move the discussion to Gitter as well, if you prefer.

**Comment by lloydmeta** [comment]
@kolemannix cool.

I totally hear you on separating Serialization concerns from data model definition. In fact I'm not too sure if mix-in style even makes sense for a Slick integration given that we need a DB `Profile` val in scope in order to do the mapping.

As for consistency, (afaik) all of integrations support both styles: the mix-in traits actually defer to a singleton method that builds the serializers (e.g. form building is [here](https://github.com/lloydmeta/enumeratum/blob/master/enumeratum-play/src/main/scala/enumeratum/Forms.scala#L115-L129), and Json formatter building is [here](https://github.com/lloydmeta/enumeratum/blob/master/enumeratum-play-json/src/main/scala/enumeratum/EnumFormats.scala)). The mix-in traits defer to those methods and are offered just as a convenience  :)

For the Slick integration, if it makes no sense, I think we can skip the mix-in traits.

**Comment by erwan** [comment]
Hi!

Is there any news on this front? I have a profile with about 60 lines of boilerplate for all my enums in Slick, that would be awesome if I could get rid of that :)

**Comment by erwan** [comment]
OK, I'll give it a shot!

**Comment by kolemannix** [comment]
I've (finally) gotten around to taking a crack at this. Looking for some initial feedback on the approach.

PR: #187
