### ISSUE TITLE
enumeratum-json4s ValueEnum example broken?

### ISSUE THREAD

**Issue by hekmekk** [lloydmeta/enumeratum#161]
When trying to implement (copy & paste really...) the [json4s integration example](https://github.com/lloydmeta/enumeratum#json4s) for `ValueEnum`, trying to define the serialization format

```scala
implicit val formats = DefaultFormats + Json4s.serializer(Device)
```

I get the following compiler error:

`Type mismatch, epxected: Enum[NotInferedA], actual: Device.type`

This is the case for both version `1.5.12` and `1.5.13`, using scala version `2.12.4`.

**Comment by lloydmeta** [comment]
Strange, I just threw the example into Ammonite (Scala 2.12.4) and it seem to work fine.

Can you put up a small repo?

```scala
Loading...
Welcome to the Ammonite Repl 1.0.3
(Scala 2.12.4 Java 1.8.0_152)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`com.beachape::enumeratum-json4s:1.5.13`
import $ivy.$

@ import enumeratum.values._
import enumeratum.values._

@ {
  sealed abstract class Device(val value: Short) extends ShortEnumEntry
  case object Device
    extends ShortEnum[Device] /* nothing extra here */  {
    case object Phone   extends Device(1)
    case object Laptop  extends Device(2)
    case object Desktop extends Device(3)
    case object Tablet  extends Device(4)

    val values = findValues
  }
  }
defined class Device
defined object Device

@ import org.json4s.DefaultFormats

import org.json4s.DefaultFormats

@

@ implicit val formats = DefaultFormats + Json4s.serializer(Device)
formats: org.json4s.Formats = org.json4s.Formats$$anon$3@3c3357c7
```

**Comment by hekmekk** [comment]
Here's an example: https://github.com/hekmekk/enumeratum-json4s-type-mismatch

Thanks for that quick reaction. Hope it's just me missing smth.

**Comment by lloydmeta** [comment]
Ah, ok this is caused by using the wrong `Json4s.serializer`. There are 2, [one for `Enum`](https://github.com/lloydmeta/enumeratum/blob/master/enumeratum-json4s/src/main/scala/enumeratum/Json4s.scala) and [another for `ValueEnum`](https://github.com/lloydmeta/enumeratum/blob/master/enumeratum-json4s/src/main/scala/enumeratum/values/Json4s.scala).

I know it can get confusing when you are mixing `Enum` with `ValueEnum`, but for various reasons, those two things aren't exactly the same thing, even though we try hard to make their APIs align 😅 

See https://github.com/hekmekk/enumeratum-json4s-type-mismatch/pull/1 for how you might fix this in your project.

**Comment by hekmekk** [comment]
I see. Completely overlooked the imports -.-
Thanks :+1:
