### ISSUE TITLE
Support for binding empty-string / invalid values for Option[PlayEnum] query string params to None instead of failing

### ISSUE THREAD

**Issue by Enalmada** [lloydmeta/enumeratum#189]
Unfortunately browsers submit input parameters even if their values are empty.  This means that input myenum value="" will send "?myenum=&..." which causes enumeratum to fail with "Cannot parse parameter myenum as an Enum".  In my specific case, myenum is a pulldown with optional filter values not required to be selected ("", All), ("MyEnum.One", One), etc.   In my routes file I have "myenum: Option[MyEnum] ?= None" and expect that myenum=&... (the case where someone submits a form with a filter pulldown left at default value of "") would return None.  
 
I believe the best thing would be for enumeratum to treat empty parameters as None for enums defined as Option in routes file.  

One solution could be making [UrlBinders.scala](https://github.com/lloydmeta/enumeratum/blob/8696e870c3093970acdb371f624a7d5a24a34d5f/enumeratum-play/src/main/scala/enumeratum/UrlBinders.scala#L78) only consider the first nonEmpty parameter: 
```
 def queryBinder[A <: EnumEntry](
    ...
  def bind(key: String, params: Map[String, Seq[String]]): Option[Either[String, A]] = {
        // params.get(key).flatMap(_.headOption).map { p =>
        params.get(key).flatMap(_.find(_.nonEmpty)).map { p =>
          val maybeBound = ...

```
It could be better to add a new QueryStringBindable that treats Option[PlayEnum] in routes different than PlayEnum but I am not sure if that is possible or actually any better than above solution. 

(BTW: thanks so much for enumeratum...I am blown away at how much better enum heavy code is with it and very sad how long I went (years!) without knowing there was a better way to do enum in scala. )

**Comment by lloydmeta** [comment]
TBH, this seems to be a bit specific to the use case of wanting to put a default empty string option on a web form that is not part of the enum, and have it ignored even if it gets sent.

In other words, I'm not quite sure that outside the context of web forms with false values, the following expectation is valid

>  In my routes file I have `myenum: Option[MyEnum] ?= None` and expect that `myenum=&` ... would return None.

My suggestion here might be to have an `All` member in your enum so that your web form options reflect the enum properly, or to have a custom `QueryStringBindable` that works for this use case?

**Comment by lloydmeta** [comment]
> It is extremely unfortunate that "&myenum=" is completely ambiguous between Some("") and None. 

The thing is, I'm not sure if it is really ambiguous; the server is being sent an empty string (`Some("")`), whereas the absence of it would correspond to `None`, and I would expect the former to bind to `Some(Blank)`, where `Blank` is an enum entry whose `entryName` is `""`, and the latter to bind to `None`.

> It is interesting that you mention false values...at the risk of a tangent... I believe the application needs to handle consequences of bind error. I believe the way UrlBinders is written now causes an english error on invalid enum.

It is a tangent, but a good one; we could definitely improve on the i18n internationalisation in this lib. Pushing it to app-level logic is probably not the way to do it though.

> An "All" member is a potential workaround. I suspect that most developers would prefer to avoid the conceptual impact of defining enums that don't correspond to actual values. (In my case when I add an enum to the code it adds it to the database if it doesn't exist and I don't ever want "All" to make it into the database)

In general, I believe this is solved by neatly separating and translating between view, domain, and persistence models. 

> I personally feel that the expectation of routes myenum: Option[MyEnum] ?= None and path myenum=& ... would return None is valid in the scope of enumeratum-play. If your gut says that some people might want Option[PlayEnum] to fail on Some(""), how do you feel about either:

So, just to confirm, `myenum: Option[MyEnum] ?= None` should already be working, as in:
  * If the query param is absent, the param is bound to `None`
  * If the query param is present, but invalid (e.g. not a `entryName` held by the enum), it gets rejected

Correct? 

The support for `Option` comes from the `bindableOption` [defined in Play](https://github.com/playframework/playframework/blob/c038bc147b03285a1de7acc50037e1e7f438bedf/framework/src/play/src/main/scala/play/api/mvc/Binders.scala#L442-L451), and the current behaviour of the binders defined in `enumeratum-play` corresponds with what the [default binders do in Play](https://github.com/playframework/playframework/blob/c038bc147b03285a1de7acc50037e1e7f438bedf/framework/src/play/src/main/scala/play/api/mvc/Binders.scala#L324-L335).  That is, if provided with an invalid value, will simply fail to bind instead of giving you `None`; e.g. if you have a binding to a `myUuid: Option[UUID] ?= None`, and the request has `myUuid=&`, it wouldn't give you `None`, it would simply fail, right?

**Comment by Enalmada** [comment]
Correct, if no parameter is passed, the route option is bound to None.  If a param is present and invalid, it gets rejected.  

The ambiguity I struggle with here is that there is no way for a web form select input to pass the absence of a form attribute (without javascript).  All play web developers have to deal with the fact that the closest thing a browser form sends is an empty string (or the figurative All).  Enumeratum is so awesome that it should be part of every play sample and it would be super convenient for everyone if optional select element support was available out of the box, even if that ment opting into different provided UrlBinders.scala files depending on how you want things to work.  It seems pretty safe and convenient to offer a UrlBinderClassic that errors on bind fail and another UrlBinderSilent that treats failures as if the parameter wasn't there.    

I suspect there is no way to perfectly handle internationalization outside the application (advanced users are going to be doing something custom like use a database)...but if enumeratum-play can tap into the default play message files behavior, changing english messages to message file keys would probably be a nice incremental improvement for i18n users.  

I am super new to binders but yes I believe route Option[UUID] with request myUuid=& would fail.  I had the same problem with routing Option[String] as I do with Option[PlayEnum]. Empty value parameter binds to Some("") rather than None.   Before enumeratum, I have always just worked around that by passing routes defined as myOption: String ?="" and handled it with a stringToOption function in my controller.  Enumeratum-play inspired me do better!  Now I am trying to make sure each web developer wanting first class routing doesn't have to reinvent the wheel of binders.

**Comment by lloydmeta** [comment]
>  Now I am trying to make sure each web developer wanting first class routing doesn't have to reinvent the wheel of binders.

The point of Play and subsequently, this lib, is to make sure that doesn't happen. There might be some differences in opinion given that not everyone uses Play for the same use-cases :)

Seeing as how I, and quite a few others have been using `enumeratum-play`, and, the default Play binders with forms, query strings, etc for a  few years now without needing the fail-invalid-values-to-None behaviour that you're suggesting, I remain somewhat skeptical that this is the right path to go (or encourage), given that we've already identified workarounds for this specific use-case (adding an enum member for your view layer and doing translations across layers, writing your own binder)

I'll leave this ticket open for a while longer to see if there is something there that will make me keener to maintain some more code, but in the mean time I've also amended the title of this ticket to be more specific.

**Comment by Enalmada** [comment]
The skepticism is completely justified and your title update is spot on.  Your workarounds will give anyone that comes along with the same issue food for thought.   I think the ticket can be closed for now as discussed/reopen if you ever feel like supporting it.  While I chew on the view layer suggestion, I will start with my own binder like this (unless you would suggest something else):
```
trait MyEnum[A <: EnumEntry] extends PlayEnum[A] { self: Enum[A] =>
  override implicit val queryBindable: QueryStringBindable[A] = MyCustomBinders.queryBinder(self)
  override implicit val pathBindable: PathBindable[A] = MyCustomBinders.pathBinder(self)
}
```

By the way, I think enumeratum needs to be here so new users can find it easier: https://www.playframework.com/documentation/2.6.x/ModuleDirectory.  Please consider submitting it unless you disagree.
