### ISSUE TITLE
Support enums with non-sealed classes / traits

### ISSUE THREAD

**Issue by eyalroth** [lloydmeta/enumeratum#206]
I just discovered this library, loving it so far :)

Would it be possible to support enums with classes / traits which are **not** sealed? i.e:

`Pokemon.scala`:
```scala
trait Pokemon extends EnumEntry

object Pokedex extends Enum[Pokemon] {
  val values = findValues
}
```

`Gen1Pokemon.scala`:
```scala
// doesn't have to be sealed really
sealed trait Gen1Pokemon extends Pokemon

case object Bulbasaur extends Gen1Pokemon
case object Ivysaur extends Gen1Pokemon
...
```

`Gen2Pokemon.scala`:
```scala
sealed trait Gen2Pokemon extends Pokemon

case object Chikorita extends Gen2Pokemon
case object Bayleef extends Gen2Pokemon
...
```

**Comment by lloydmeta** [comment]
Hmm, no, that won't be supported, probably ever because

1. The `findValues` macro needs to expand into a sequence of members at compile time, but there is no guarantee that `Pokenmon` is itself an enum; the trait is open and could be inherited and used in, say, other projects that import this trait.
2.  The way Enumeratum's macro works; it only searches for children classes inside the current body that contains `findValues`; why?
  1. The `knownDirectSubclasses` reflection method is/was flakey at the time of writing, so searching for children classes of a given type was problematic
  2. Even if (1) was fixed definitively, it returns a `Set` of members, so it can't guarantee ordering.

Hopefully that answers your question.  I'll close this now but feel free to ask more questions 😄

**Comment by lloydmeta** [comment]
I'm not really sure if there are any enum implementations in any language that let you define enums in that way.  Good luck in your search and it would be great if you could let me know if you find anything like that 😄
