### ISSUE TITLE
update uPickle dependency

### ISSUE THREAD

**Issue by bassmake** [lloydmeta/enumeratum#213]
Actual version of enumeratum-upickle uses 0.4.4 version of uPickle and is not compatible with actual 0.7.1 version

**Comment by lloydmeta** [comment]
Yeah, to be honest, I haven't updated that module in 2 years, and IIRC I added it when UPickle was the only ScalaJS JSON lib in the ecosystem, then it kind of died, and now is back again.  I had been on the fence about keeping it around due to not being sure how many people really use it in the wild.

Would you like to submit a PR to bump the version?

**Comment by bassmake** [comment]
Not really, as I ended up with play-json.

**Comment by lloydmeta** [comment]
Fair enough. Closing as I've removed the integration.
