### ISSUE TITLE
Nested ValueEnums don't work

### ISSUE THREAD

**Issue by randomstatistic** [lloydmeta/enumeratum#60]
I'm converting some of my stuff to the StringEnumEntry, (Thanks!) and I'm noticing a few things I did earlier (With stock EnumEntry) that don't work with this. It's quite possible the answers will be "don't do that".

I'd set up an object with all the objects associated with a use case. This allowed a single easy import statement to get all the relevant symbols. This doesn't compile:

```scala
sealed abstract class ParameterName(val value: String) extends StringEnumEntry
object ParameterConstants extends StringEnum[ParameterName] {
  object FOO extends ParameterName("foo")

  override def values = findValues

  sealed abstract class FooValue(val value: String) extends StringEnumEntry
  object FooValues extends StringEnum[FooValue] {
    object A extends FooValue("a")
    object B extends FooValue("b")

    override def values = findValues
  }

}
```

**Comment by lloydmeta** [comment]
Hi there,

I understand why you might want to do this, but unfortunately, it seems that during macro expansion, the type of the construction call isn't yet typed for nested types. This is similar to the reason why I couldn't support `ValueEnum`s for Scala 2.10 (except in that case, nested or not, the construction method call wasn't typed..).

For your reference, the relevant details are [here](https://github.com/lloydmeta/enumeratum/blob/master/macros/compat/src/main/scala-2.11/enumeratum/ValueEnumMacros.scala#L103). 

My current thought is to add a match case for `case Apply(fun, _) if fun.tpe == null` right above that line, and abort with a helpful message, such as `"The constructor call has not yet been typed. Perhaps you are nesting ValueEnums (unsupported)?"`. What are your thoughts?

**Comment by LPTK** [comment]
@lloydmeta 

Have you considered nesting the whole enum _inside_ the macro instead of having the macro look outside of its scope (something they are not "supposed" to do)?

As in:
```
val MyEnum = findValues {
  sealed class MyEnum extends EnumEntry
  new Enum[MyEnum] { ... }
}
```

I think `findValues` can return a structural type with the right stuff in it, and can be given a signature that will satisfy the IDE's.

I imagine you have tried this kind of approaches, but it'd be interesting to know what problems you had with them.

**Comment by lloydmeta** [comment]
@LPTK,

Thanks for your input! Yeah, doing something along those lines has been on my mind for a while now ever since the Scala team made clear their views on how macros should behave moving forward. However, something like that is a big API change for this library, and if we're honest, probably a bit clunky. Also, thus far I've got 2.12 building and passing tests so it might not be necessary just yet ;)

Having said that, I'm not sure if it will help with this problem (during macro expansion calls to the constructor of the nested class, `FooValue`, are not typed, for instance in `object A extends FooValue("a")`). If you know otherwise, I would love to hear it (a PR would also be greatly appreciated :))

**Comment by LPTK** [comment]
In my understanding, any tree you pass to a def macro is fully typed beforehand.

So in our case, first scalac will type check  the inner class `FooValue` _and_ what we pass to `findValues`, which is the `StringEnum[FooValue]` instantiation containing `object A extends FooValue("a")`. Then only the inner `findValues` macro will execute, and it will be able to pick up type info from that tree.

Am I missing something?

**Comment by lloydmeta** [comment]
Ah ok, I had either never known or forgotten that trees passed to macros are fully typed beforehand :)

It sounds like it could work, and it would be interesting to see what the most friendly API for it would look like (incl. non-nested case, which is the 99% I think..).

**Comment by LPTK** [comment]
Agreed. I may look into a prototype to find out when I have time ;-)

**Comment by lloydmeta** [comment]
Added support for this by switching a few things in the way constructor parameters are resolved. Added a [test case](https://github.com/lloydmeta/enumeratum/blob/master/enumeratum-core/compat/src/test/scala-2.11/enumeratum/values/Animal.scala#L9-L32) for it too.
